environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python27"
    #- PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python34"
    #- PYTHON: "C:\\Python34-x64"
    #- PYTHON: "C:\\Python35"
    #- PYTHON: "C:\\Python35-x64"
    #- PYTHON: "C:\\Python36"
    #- PYTHON: "C:\\Python36-x64"

    
    
build: off


install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools six cython sphinx wheel future decorator"
  - '%PYTHON%\\python.exe -m pip install --upgrade FXrays cypari networkx pypng'
  - 'C:\\Python27\\python.exe -m pip install "pyx<0.13" "ipython<6.0"'
  - 'C:\\Python27\\python.exe -m pip install --no-index --find=file:wheelhouse apsw'
  - 'C:\\Python36\\python.exe -m pip install pyx ipython'
  # Hoping we don't need these anymore
  #- 'C:\\Python27\\python.exe -m pip install https://bitbucket.org/nathan_dunfield/pyinstaller_windows/downloads/PyInstaller-3.3.dev0+ga98be396.mod-py2-none-any.whl'
  #- 'C:\\Python36\\python.exe -m pip install https://bitbucket.org/nathan_dunfield/pyinstaller_windows/downloads/PyInstaller-3.3.dev0+ga98be396.mod-py3-none-any.whl'
  - '%PYTHON%\\python.exe -m pip install "PyInstaller==3.3"'
  - '%PYTHON%\\python.exe -c "import tkinter; print(tkinter.TkVersion)"'
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  
  # Togl
  #- cd togl\win-tk8.6
  #- make-togl.bat

  # PLink
  - hg clone https://bitbucket.org/t3m/plink
  - cd plink
  - "%PYTHON%\\python.exe setup.py release --install"
  - cd ..

  # snappy_manifolds
  - hg clone https://bitbucket.org/t3m/snappy_manifolds
  - cd snappy_manifolds
  - "%PYTHON%\\python.exe setup.py release --install"
  - cd ..
  - "%PYTHON%\\python.exe -m snappy_manifolds.test"
  - '%PYTHON%\\python.exe -c "import snappy_manifolds; print(snappy_manifolds.__version__)"'

  
  # Spherogram
  - hg clone https://bitbucket.org/t3m/spherogram
  - cd spherogram
  - "%PYTHON%\\python.exe setup.py release --install"
  - cd ..

  # SnapPy
  - hg clone https://bitbucket.org/t3m/snappy
  - cd snappy
  - "%PYTHON%\\python.exe setup.py release --install"
  - cd windows_exe
  - "%PYTHON%\\python.exe make.py"
  - "%PYTHON%\\python.exe -m snappy.test"


artifacts:
  - path: plink\dist\*.tar.gz
  - path: spherogram\dist\*.tar.gz
  - path: spherogram\dist\*.whl
  - path: snappy\dist\*.tar.gz
  - path: snappy\dist\*.whl
  - path: snappy\windows_exe\InstallSnapPy*.exe
  
