name: sdist

on: [push, pull_request]


jobs:
  sdist:
    name: build sdist tarballs
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: |
          python -m pip install cython sphinx wheel decorator
          python -m pip install cypari knot_floer_homology


      - name: Install PLink
        run: |
          git clone https://github.com/3-manifolds/plink
          cd plink
          python setup.py pip_install
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: ./*/dist/*.tar.gz
          path: ./plink/dist/*.whl
          

