name: sdist

on: [push, pull_request]


jobs:
  sdist:
    name: build sdist tarballs
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: opengl sys package
        run: sudo apt install libglu1-mesa-dev

      - name: python packages
        run: |
          python -m pip install cython wheel decorator sphinx sphinx_rtd_theme
          python -m pip install cypari knot_floer_homology FXrays

      - name: plink
        run: |
          git clone https://github.com/3-manifolds/plink
          cd plink
          python setup.py pip_install
          python setup.py sdist

      - name: low_index
        run: |
          git clone https://github.com/3-manifolds/low_index
          cd low_index
          python -m pip install .
          python setup.py sdist

      - name: manifolds
        run: |
          git clone https://github.com/3-manifolds/snappy_manifolds
          cd snappy_manifolds
          python setup.py pip_install
          python setup.py sdist

      - name: 15 knots
        run: |
          git clone https://github.com/3-manifolds/snappy_15_knots
          cd snappy_15_knots
          python setup.py pip_install
          python setup.py sdist

      - name: spherogram
        run: |
          git clone https://github.com/3-manifolds/spherogram
          cd spherogram
          python setup.py pip_install
          python setup.py sdist

      - name: snappy
        run: |
          git clone https://github.com/3-manifolds/snappy
          git switch 3.1.1
          cd snappy
          python setup.py pip_install
          python setup.py sdist

      - name: test
        run: python -m snappy.test --skip-modern-opengl

      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: |
            ./*/dist/*.tar.gz
            ./plink/dist/*.whl
            ./snappy_manifolds/dist/*.whl
            ./snappy_15_knots/dist/*.whl
